Metamask errors
wakeuplabs-io/arbitrum-transaction-enforcer pull request #50
Opened 2024-08-14 22:17 UTC by FacuDeLorenzo

Solves [ARBT-41](https://wakeuplabs.atlassian.net/browse/ARBT-41)

- Added alert global functionality.
- Alert uses context and renders an alert on the root.
- Alert can parse metamask errors.

https://github.com/user-attachments/assets/d81e9437-0943-4421-848e-4c973978b4db

2024-08-15 17:01 UTC, njaume requested changes

2024-08-15 17:01 UTC, njaume commented on packages/ui/src/contexts/alert-context.tsx
> +		<AlertContext.Provider value={values}>
Would be better to separate the context from ui, maybe you can create a alert component that consumes it and shows the dialog modal, just in case you need to consume the context without using the ui. Just a comment keep or leave it

2024-08-15 20:55 UTC, merged

2024-08-20 12:48 UTC, juandahl reviewed
LGTM

2024-08-20 12:48 UTC, juandahl commented on packages/ui/src/components/error-alert.tsx
> +}
should be an util? I think it is a good function to reuse.

2024-08-20 12:48 UTC, juandahl commented on packages/ui/src/components/error-alert.tsx
> +function parseErrorReason(serializedCause: any) {
You could avoid the any(when you use it), casting the response as string